### PR TITLE
Fixes for build warnings, failure with node 6.9.0

### LINKED ISSUE #591: npm run start fails with error message
The following error is displayed:

```bash 
ERROR in ./src/components/update-service/update-service.controller.ts
(246,63): error TS2345: Argument of type 'string[][]' is not assignable to parameter of type 'Many<PropertyName>'.
  Type 'string[][]' is not assignable to type 'PropertyName[]'.
    Type 'string[]' is not assignable to type 'PropertyName'.
      Type 'string[]' is not assignable to type 'symbol'.

ERROR in ./src/components/update-service/update-service.controller.ts
(247,45): error TS2345: Argument of type 'string[][]' is not assignable to parameter of type 'Many<PropertyName>'.
  Type 'string[][]' is not assignable to type 'PropertyName[]'.
```

I haven't tried to run the catalog standalone in a good while, so I'm not sure if this is a legitimate error or if standalone serve has fallen by the wayside (ie, works fine if running with `bower link` to console).  

@jeff-phillips-18 @spadgett @jwforres

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Fixes #591

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
ha! good ol' any 😄  

i need to get into TS more.

File: app/app.ts [hunk 1]
```diff
@@ -67,7 +67,7 @@ angular
   .component('logoutpage', logoutPage)
   .component('navigation', navigation)
   .constant('amTimeAgoConfig', {titleFormat: 'LLL'})
-  .run(function(IS_IOS) {
+  .run(function(IS_IOS: any) {
```
Comment (benjaminapetersen) [inline app/app.ts]: Ignorance question, but is there a better annotation than `any` for things like this? It appears that `IS_IOS` is a `bool` so annotating with type `bool` would make sense.  I could be wrong, tho.

I've been wondering about similar things like `DataService: any`.  What is best practice for an annotation that should resolve to a specific service singleton?

Comment (jeff-phillips-18) [reply app/app.ts]: I could use boolean here.

Comment (jeff-phillips-18) [reply app/app.ts]: Largely we have ignored typing in this repo. I've added issue #593 to address this concern.

Comment (benjaminapetersen) [reply app/app.ts]: Yeah, there is a lot of `any`.  I'd def like to see a file or two that somewhat follows best practices, so that if we wanted to fix it we could.

**Comment by benjaminapetersen** [comment]
Nice. Need to cut a release now?

**Comment by jeff-phillips-18** [comment]
I don't believe this warrants a release.

**Comment by benjaminapetersen** [comment]
Yup, pulled the change fine w/o it.
