### PR TITLE
Close the overlay panel on ESC

### LINKED ISSUE #326: Accessibility: Escape key should close the overlay
Suggested by @ncameronbritt, and I've had the same thought. I've tried to close the overlay with the escape key before, and it doesn't work. It's potentially an accessibility issue and inconsistent with our other Bootstrap modals.

Maybe we can optionally prompt if the user has typed something.

cc @openshift/team-ux-review

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Fixes #326

### CODE REVIEW

File: src/components/overlay-panel/overlay-panel.controller.ts [hunk 1]
```diff
@@ -37,10 +43,22 @@ export class OverlayPanelController implements angular.IController {
...
 
   private hideDialog = () => {
     this.ctrl.shown = false;
     $('body').removeClass('overlay-open');
-  }
+    this.$document.unbind('keydown keypress', this.closeOnEsc);
+  };
+
+  private closeOnEsc = (event: any) => {
+    console.log("Keydown: " + event.which);
```
Comment (spadgett) [inline src/components/overlay-panel/overlay-panel.controller.ts]: remove console log

**Comment by jeff-phillips-18** [comment]
Removed the console.log.  @spadgett tested and it does not close when esc on a ui-select.
